source 'http://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.18', '< 0.5'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem "font-awesome-rails"
gem 'bootstrap-sass', '~> 3.3.1'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password

# active link
gem 'active_link_to'

# upload file
gem 'paperclip'
#gem 'carrierwave'
#gem 'mini_magick', '~> 4.3'
#gem 'carrierwave-dropbox'
#gem 'dropbox'
gem 'dropzonejs-rails'

gem 'bcrypt', '~> 3.1.11'
gem 'momentjs-rails', '>= 2.8.1'
gem 'bootstrap3-datetimepicker-rails', '4.7.14'
gem 'filterrific'
gem 'will_paginate'
gem 'will_paginate-bootstrap'

# to get the list of country
gem 'country-select'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
gem 'rails-controller-testing'
gem 'bootstrap-modal-rails'

gem 'fullscreenslider-rails'
gem 'private_pub'
gem 'thin'

gem 'slick_rails'
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
